Determine architecture we're running on at runtime

diff --git a/bin/networkmanager b/bin/networkmanager
--- a/bin/networkmanager
+++ b/bin/networkmanager
@@ -13,9 +13,19 @@ mkdir -p $SNAP_APP_DATA_PATH/run/sendsigs.omit.d
 mkdir -p $SNAP_APP_DATA_PATH/var/run
 mkdir -p $SNAP_APP_DATA_PATH/var/lib
 
-# XXX hardcoded architecture
+TRIPLET=
+
+case $SNAP_ARCH in
+    amd64)
+        TRIPLET=x86_64-linux-gnu
+        ;;
+    *)
+        echo "ERROR: Architecture $SNAP_ARCH isn't supported by this snap"
+        exit 1
+esac
+
 # TODO drop DEBUG
-LD_LIBRARY_PATH="$SNAP_APP_PATH/usr/lib/x86_64-linux-gnu:$SNAP_APP_PATH/usr/lib/x86_64-linux-gnu/NetworkManager:$SNAP_APP_PATH/lib/x86_64-linux-gnu" \
+LD_LIBRARY_PATH="$SNAP_APP_PATH/usr/lib/$TRIPLET:$SNAP_APP_PATH/usr/lib/$TRIPLET/NetworkManager:$SNAP_APP_PATH/lib/$TRIPLET" \
 $SNAP_APP_PATH/usr/sbin/NetworkManager \
     --state-file=$SNAP_APP_DATA_PATH/NetworkManager.state \
     --config-dir=$SNAP_APP_PATH/etc/NetworkManager \
