hooks: add WoWLAN configuration items

diff --git a/hooks/configure b/hooks/configure
--- a/hooks/configure
+++ b/hooks/configure
@@ -5,13 +5,13 @@ switch_wifi_powersave() {
   # See https://developer.gnome.org/libnm/stable/NMSettingWireless.html#NMSettingWirelessPowersave
   # for the meaning of the different values for the wifi.powersave option.
   case $1 in
-    enable)
+    enabled)
       cat <<EOF > $path
 [connection]
 wifi.powersave = 3
 EOF
       ;;
-    disable)
+    disabled)
       cat <<EOF > $path
 [connection]
 wifi.powersave = 2
@@ -23,11 +23,63 @@ EOF
   esac
 }
 
+switch_wifi_wake_on_wlan() {
+  value=0
+  # See `man nm-settings` for details about those values. They
+  # correspond to the enum NMSettingWirelessWakeOnWLan defined
+  # in libnm-core. NetworkManager only allows us to set integer
+  # values here.
+  case "$1" in
+    disabled)
+      value=0
+      ;;
+    global)
+      value=1
+      ;;
+    any)
+      value=2
+      ;;
+    magic)
+      value=8
+      ;;
+    all)
+      value=510
+      ;;
+    *)
+      echo "ERROR: Invalid value provided for wifi.wake-on-wlan"
+      exit 1
+      ;;
+  esac
+  password=$2
+  path=$SNAP_DATA/conf.d/wifi-wowlan.conf
+
+  echo "[connection]" > $path
+  # If we don't get a value provided there is no one set in the snap
+  # configuration and we can simply leave it out here and let
+  # NetworkManager take its default one.
+  if [ -n "$value" ]; then
+    echo "wifi.wake-on-wlan=$value" >> $path
+  fi
+  if [ -n "$password" ]; then
+    echo "wifi.wake-on-wlan-password=$password" >> $path
+  fi
+}
+
 value="`snapctl get wifi.powersave`"
 if [ -n "$value" ]; then
   switch_wifi_powersave $value
 else
-  default="disable"
+  default="disabled"
   snapctl set wifi.powersave=$default
   switch_wifi_powersave $default
+fi
+
+value=`snapctl get wifi.wake-on-wlan`
+password=`snapctl get wifi.wake-on-wlan-password`
+if [ -n "$value" ] || [ -n "$password" ]; then
+  switch_wifi_wake_on_wlan $value "$password"
+else
+  snapctl set wifi.wake-on-wlan=disabled
+  snapctl set wifi.wake-on-wlan-password=
+  switch_wifi_wake_on_wlan disabled ""
 fi
